### ISSUE TITLE
It's not work in 1.27a

### ISSUE THREAD

**Issue by RedLove** [UnryzeC/MemHackAPI#1]
---------------------------------------
              JASS ERROR
---------------------------------------
超过了字节码限制

stack traceback:
    [WriteRealMemory:35]
    [fast_call_5:129]
    [this_call_4:19]
    [SetCSimpleFontStringFont:40]
    [CreateButtonCooldown:48]
    [DrawAllButtonCooldowns:87]
---------------------------------------

**Comment by UnryzeC** [comment]
Please make sure to follow the provided example on how to enable MemHack, 1.27a is no different from 1.26a in terms of bytecode "execution", only versions 1.27b and higher have their own quirks. Also, I can't really understand what this "traceback" is supposed to tell me.

Also, where and how are you getting these errors/warnings?

**Comment by RedLove** [comment]
The log source from Console.It means `Bytecode limit exceeded`.
<img width="403" alt="image" src="https://user-images.githubusercontent.com/8992637/167345038-277b85d8-494a-479c-b185-3766a27fe031.png">


I launched the MemHackApiV1.6 from YDWE.
I think the api is embbed,may be no need JNGP.
<img width="210" alt="image" src="https://user-images.githubusercontent.com/8992637/167345003-5e18f11a-70a4-49b6-ae6e-73093e88fbe9.png">

**Comment by UnryzeC** [comment]
I am not quite sure what you are saying, but it seems you were able to fix the issue yourself. :)

JNPG is simply what I use to "build" MemHack, and since it works, I can rely on it and I can suggest it. YDWE for me is mostly pointless and honestly it's way too clunky.
