### ISSUE TITLE
It's give a error when build in ydwe

### ISSUE THREAD

**Issue by RedLove** [UnryzeC/MemHackAPI#2]
<img width="930" alt="image" src="https://user-images.githubusercontent.com/8992637/167340531-59934443-4b3e-4a52-9299-c1c218769999.png">

**Comment by RedLove** [comment]
the game will crash or launch failded when i build MemHackApi by `Jass New Gen Pack Rebuild`.

<img width="423" alt="image" src="https://user-images.githubusercontent.com/8992637/167346610-bcef0947-7925-4330-ba86-41bbb750af13.png">

**Comment by UnryzeC** [comment]
Please use this JNPG: https://xgm.guru/p/wc3/jassnewgenpack-r along with the pjass.exe that I provide in the resource: https://github.com/UnryzeC/MemHackAPI/blob/main/JassHelper/pjass.exe and do the following:

After you download JNPG, download pjass.exe from my project's folder JassHelper and replace it in JassHelper folder where JNPG was installed.

YDWE - is not something I can or care to support, I am working on JNPG and it works with these options:

![image](https://user-images.githubusercontent.com/95709901/167391149-6d8cfe6e-c331-4f64-b13a-3fbaab5869ce.png)
![image](https://user-images.githubusercontent.com/95709901/167391192-c397be80-d64f-408a-8444-dd76b5f60b27.png)
